name: publish-docker

on:
  push:
    branches:
      - master

env:
  HUB: shaogd

jobs:
  release:
    runs-on: ubuntu-latest
    name: Start release process
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          username: shaogd
          password: ${{ secrets.HUB_TOKEN }}
      - name: Build docker image
        run: |
          cd 5
          docker buildx create --use --driver docker-container --name sonarqube > /dev/null 2>&1 || true
          docker buildx build --platform linux/arm64,linux/amd64 --push   --no-cache   -t $(HUB)/sonar-scanner-cli:v5  --provenance=false .
          docker buildx rm sonarqube || true
